server:
  port: 2003
logging:
  level:
    root: INFO
  path: /data/log 
spring:
  application:
    name: shiro-demo
#datasource
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.38.12:3306/db_msg?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 'blf1#root'
#jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
#freemark
  freemarker:
    tempalte-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html 
  redis:
    host: 120.78.76.207
    port: 6379
    timeout: 5000
    